# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 057fc85baf0a52a36b67ebceaaebd098c55a22b46b06c1a455a7e68a5a79253e7ea12f21fb40f062744354adf71580be1ec944eb71d09867867c72546437c61c

test:
  secret_key_base: 6f1573afb91338d081b7fd08669bcb026eef95d11ba0eca2b66bf235048dd6e7bf5db53a03fc58688c7b87a62c3f81bd1edb6819708a22f70ecfc31924446913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
